---
image: maven:3.3.9-jdk-8

pipelines:
  default:
    - step:
        name: 'Test'
        caches:
          - maven
        script:
          - apt-get update
          - apt-get install -y build-essential
          - apt-get install -y python python-dev python-pip python-virtualenv
          - apt-get install -y node npm
          - mvn --batch-mode clean test
