/*
 * Copyright (c) 2019 Daniel Aharon
 */

package us.aharon.monitoring.core.db

import com.amazonaws.services.dynamodbv2.datamodeling.*

import java.time.ZonedDateTime


/**
 * DynamoDB record for notification events.
 * Record notifications that have been sent and the check results that triggered them.
 *
 * The table name is dynamically defined in [TableNameResolver].
 */
@DynamoDBTable(tableName = "DYNAMICALLY_DEFINED")
internal data class NotificationRecord(
        @DynamoDBHashKey
        @DynamoDBNamed("pk")
        var handler: String? = null,

        @DynamoDBAttribute
        @DynamoDBNamed("result_id")
        var resultId: String? = null,

        @DynamoDBAttribute
        var description: String? = null

) {
    @DynamoDBRangeKey
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAutoGenerated(generator = DynamoDBTimestampGenerator::class)
    @DynamoDBTypeConverted(converter = ZonedDateTimeConverter::class)
    @DynamoDBNamed("sk")
    var timestamp: ZonedDateTime? = null

    @DynamoDBAttribute
    @DynamoDBNamed("data")
    var data: String? = DATA_FIELD

    companion object {
        const val DATA_FIELD = "NOTIFICATION"
    }
}
