---
AWSTemplateFormatVersion: 2010-09-09
Description: Monitoring

Resources:

  ##
  # Lambda Functions
  ##
  MonitoringClientRegistration:
    Type: AWS::Lambda::Function
    Properties:
      Description: Register clients with the monitoring system.
      Runtime: java8
      Handler: '${clientRegistrationHandler}'
      Code:
        S3Bucket: '${codeS3Bucket}'
        S3Key: '${codeS3Key}'
      Role: !GetAtt MonitoringClientRegistrationRole.Arn
      Timeout: 60
      MemorySize: 512
      Tags:
        - Key: App
          Value: Monitoring

  MonitoringCheckScheduler:
    Type: AWS::Lambda::Function
    Properties:
      Description: Fire events to the SNS Fanout Topic.
      Runtime: java8
      Handler: '${checkSchedulerHandler}'
      Code:
        S3Bucket: '${codeS3Bucket}'
        S3Key: '${codeS3Key}'
      Role: !GetAtt MonitoringCheckSchedulerRole.Arn
      Timeout: 60
      MemorySize: 512
      Tags:
        - Key: App
          Value: Monitoring

  ##
  # IAM Roles
  ##
  MonitoringClientRegistrationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /monitoring/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  MonitoringCheckSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /monitoring/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole

  ##
  # Scheduled Events
  ##
  MonitoringCheckSchedulerEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Monitoring check scheduler event rule.
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !GetAtt MonitoringCheckScheduler.Arn
          Id: MonitoringCheckScheduler

  MonitoringCheckSchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MonitoringCheckScheduler
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MonitoringCheckSchedulerEventRule.Arn

  ##
  # SNS Topics
  ##
#  MonitoringAlertSNSTopic:
#    Type: AWS::SNS::Topic
#    Properties:
#      DisplayName: buttinski-alerts
