---
AWSTemplateFormatVersion: 2010-09-09
Description: Monitoring

Resources:

  ##
  # Lambda Functions
  ##
  MonitoringClientRegistration:
    Type: AWS::Lambda::Function
    Properties:
      Description: Register clients with the monitoring system.
      Runtime: java8
      Handler: '${clientRegistrationHandler}'
      Code:
        S3Bucket: '${codeS3Bucket}'
        S3Key: '${codeS3Key}'
      Role: !GetAtt MonitoringClientRegistrationRole.Arn
      Timeout: 60
      MemorySize: 512
      Tags:
        - Key: App
          Value: Monitoring

  MonitoringCheckScheduler:
    Type: AWS::Lambda::Function
    Properties:
      Description: Fire events to the SNS Fanout Topic.
      Runtime: java8
      Handler: '${checkSchedulerHandler}'
      Code:
        S3Bucket: '${codeS3Bucket}'
        S3Key: '${codeS3Key}'
      Role: !GetAtt MonitoringCheckSchedulerRole.Arn
      Timeout: 60
      MemorySize: 512
      Tags:
      - Key: App
        Value: Monitoring

  ##
  # IAM Roles
  ##
  MonitoringClientRegistrationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /monitoring/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
#      Policies:
#      - PolicyName: SNSTopics
#        PolicyDocument:
#          Version: 2012-10-17
#          Statement:
#          - Effect: Allow
#            Action:
#            - sns:Publish
#            Resource:
#            - !Ref MonitoringAlertSNSTopic

  MonitoringCheckSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /monitoring/
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
  #      Policies:
  #      - PolicyName: SNSTopics
  #        PolicyDocument:
  #          Version: 2012-10-17
  #          Statement:
  #          - Effect: Allow
  #            Action:
  #            - sns:Publish
  #            Resource:
  #            - !Ref MonitoringAlertSNSTopic

  ##
  # SNS Topics
  ##
#  MonitoringAlertSNSTopic:
#    Type: AWS::SNS::Topic
#    Properties:
#      DisplayName: buttinski-alerts
